=== S3ll4rd0/Ejercicio-XML-XSD/XSD Delivery/Exercise2.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="File">
<xs:complexType>
    <xs:sequence maxOccurs="unbounded">
        <xs:element name="Agency" maxOccurs="unbounded">
        <xs:complexType>
            <xs:all>
                <xs:element name="Name" type="xs:string"></xs:element>
                <xs:element name="E-Mail" type="xs:string"></xs:element>
                <xs:element name="Phone">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:pattern value="[0-9]{12}"></xs:pattern>
                    </xs:restriction>
                </xs:simpleType>
                </xs:element>
            </xs:all>
        </xs:complexType>
        </xs:element>

        <xs:element name="Owners" minOccurs="1" maxOccurs="unbounded">
        <xs:complexType>

            <xs:all>
                <xs:element name="Name" type="xs:string"></xs:element>
            </xs:all>

            <xs:attribute name="ID" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:pattern value="[0-9]{8}"></xs:pattern>
                </xs:restriction>
            </xs:simpleType>
            </xs:attribute>

        </xs:complexType>
        </xs:element>

        <xs:element name="Flats">
        <xs:complexType>

            <xs:sequence>
                <xs:element name="Description" type="xs:string"></xs:element>
                <xs:element name="Value" type="xs:string"></xs:element>
            </xs:sequence>

            <xs:attribute name="ID" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z0-9]{7}"></xs:pattern>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            
            <xs:attribute name="Comfort" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="A|B|C|D|E|F"></xs:pattern>
                </xs:restriction>
            </xs:simpleType>
            </xs:attribute>

            <xs:attribute name="Squared-Meters" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="40"></xs:minInclusive>
                    <xs:maxInclusive value="400"></xs:maxInclusive>
                </xs:restriction>
            </xs:simpleType>
            </xs:attribute>

        </xs:complexType>
        </xs:element>
    </xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== S3ll4rd0/Ejercicio-XML-XSD/XSD Delivery/Exercise2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<File xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="exercise2.xsd">

<Agency>
    <Name>Miami</Name>
    <E-Mail>miami539@buyrent.com</E-Mail>
    <Phone>010513215539</Phone>
</Agency>

<Owners ID="58448143">
    <Name>Mike Holloway</Name>
</Owners>

<Flats ID="PR10001" Comfort="B" Squared-Meters="150">
    <Description>
        Beautiful place located near the main beach. 
        Just 5 minutes walk to the center of town, very cozy, 
        very well maintained, in a very quiet urbanization, 
        a very charming apartment with great views.
    </Description>
    <Value>800.000$</Value>
</Flats>

<Agency>
    <Name>Miami</Name>
    <E-Mail>miami539@buyrent.com</E-Mail>
    <Phone>010513215539</Phone>
</Agency>

<Owners ID="58448143">
    <Name>Mike Holloway</Name>
</Owners>

<Flats ID="PR10002" Comfort="A" Squared-Meters="120">
    <Description>
        Wonderful apartment located in the heart of the city, 
        is just 10 minutes walk from the bay. 
        Beautiful views of the beach.
    </Description>
    <Value>700.000$</Value>
</Flats>

</File>
