=== S3ll4rd0/Ejercicio-XML-XSD/Exercise1-XML XSD/exercise1.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="solicitud"/>

        <xs:element name="datos"/>
            <xs:element name="nombre" type="xs:string"></xs:element>
            <xs:element name="apellidos" type="xs:string"></xs:element>
            <xs:element name="DNI" type="xs:string"></xs:element>

        <xs:element name="notificaciones"/>
            <xs:element name="domicilio" type="xs:string"></xs:element>
            <xs:element name="CP">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:totalDigits value="5"></xs:totalDigits>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

        <xs:element name="matricula">
            <xs:complexType></xs:complexType>
        </xs:element>
        
</xs:schema>

=== S3ll4rd0/Ejercicio-XML-XSD/Exercise1-XML XSD/exercise1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<solicitud xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="exercise1.xsd">
    <datos>
        <nombre></nombre>
        <apellidos></apellidos>
        <DNI></DNI>
    </datos>

    <notificaciones>
        <domicilio></domicilio>
        <CP>12345</CP>
    </notificaciones>

    <matricula codigo="03010132"/>
</solicitud>
